Settings:
  #设置插件前缀
  pluginPrefix: "&7[&aRegionInfoRe&7]"
  #设置选择工具 默认为金锄头
  tool: "GOLDEN_HOE"
  #设置玩家进入服务器时是否自动开启对应功能
  activeOnPlayerJoin:
    #生物群系提示
    biome: true
    #自定义区域提示
    region: true
  #生态群系是否高精度显示，设置为false时, 如 SAVANNA与SAVANNA_ROCK两个群系切换时,无消息提示
  biomeHighAccuracy: true
  #设置检测强度,数字越低消耗越高,建议生态群系设置为50或100，自定义区域设置为20 (整数！！！)
  biomeSpeed: 100
  regionSpeed: 20

Tips:
  Single:
    #未知指令
    unknowCommand: " 未知指令! 请使用/rir help"
    #设置插件重载信息 RIR.admin
    reload: " 插件已重载!"
    #进入区域创建模式消息提示 RIR.admin
    createModeSwitch: " 创建模式已%Action%!"
    #没有权限
    noPermission: " 你没有权限!"
    #错误的指令使用方式
    wrongUsage: " 指令输入出错! 请使用/rir help"
    #生态群系提示开关时提示 %Action%为占位符,表示开启或关闭 RIR.switch.biome
    biomeSwitch: " 生物群系提示已%Action%!"
    #自定义区域提示开关时提示 RIR.switch.region
    regionSwitch: " 区域提示已%Action%!"
    #选中第一个方块
    firstPoint: " 选择第一个点: %Point%"
    #选中第二个方块
    secondPoint: " 选择第二个点: %Point%"
    #点位不足
    pointNotEnough: " 你选择的点位不足!"
    #创建成功
    createSuccessfully: " 成功创建区域,请在config.yml中修改配置"
    #未在区域内显示的内容
    noRegion: "野外"
  Entry:
    #生物群系消息提示内容，
    #[MSG] 发送消息
    #[TILE] 发送标题 使用::分割属性 主标题::副标题::淡入时间::停留时间::淡出时间
    #[ACB] ACTION_BAR消息
    #[CCOM] 控制台指令 不用加/
    #[PCOM] 玩家指令 不用加/
    biomeInfos:
      - "[ACB]-&b%oldBiome%&a->&b%newBiome%"
    #帮助菜单
    helpTips:
      - "&7RegionInformationReload:"
      - "&7/rir check <regionUniqueId> - 查看区域详细信息 #RIR.admin"
      - "&7/rir create <type> <regionUniqueId> - 创建一个type类型的新区域(需要点位选择) #RIR.admin"
      - "&7/rir createMode - 进入点位选择模式(手持config中的tool) #RIR.admin"
      - "&7/rir help - 打开帮助菜单 #RIR.help"
      - "&7/rir reload - 重载插件 #RIR.admin"
      - "&7/rir switch <biome/region> - 打开/关闭功能 #RIR.switch.biome/region"

#区域设置
Regions:
  #区域的唯一ID
  region1:
    #区域名
    name: "&ctestCube"
    #世界
    world: "world"
    #区域种类
    type: "cube"
    #正方形区域的两个对角点即可
    X1: 481
    Y1: 69
    Z1: 61
    X2: 489
    Y2: 64
    Z2: 51
    #区域进入提示
    inInfos:
      - "[MSG]-&e[&c!&e] &a你进入了%name%&a!"
      #下面的实例是主标题为空的Title
      - "[TITLE]-::%name%::10::20::10"
      - "[CCOM]-give %player% arrow 1"
      - "[PCOM]-say im noob"
    #区域离开提示
    outInfos:
      - "[TITLE]-::%name%::0::0::40"
  region2:
    #区域名
    name: "&ctestBall"
    #世界
    world: "world"
    #区域种类
    type: "ball"
    #球心坐标与球的半径
    centerX: 503.5
    centerY: 63
    centerZ: 50.5
    radius: 5
    #区域进入提示
    inInfos:
      - "[MSG]-&e[&c!&e] &a你进入了%name%&a!"
      #下面的实例是主标题为空的Title
      - "[TITLE]-::%name%::10::20::10"
    #区域离开提示
    outInfos:
      - "[TITLE]-::%name%::0::0::40"

Biomes:
  #根据需求自行补齐吧~
  #https://bukkit.windit.net/javadoc/org/bukkit/block/Biome.html
  #https://baike.baidu.com/item/%E7%94%9F%E7%89%A9%E7%BE%A4%E7%B3%BB/18860326?fr=aladdin

  BADLANDS: "恶地"
  BAMBOO_JUNGLE: "竹林"
  BASALT_DELTAS: "玄武岩三角洲"
  BEACH: "沙滩"
  BIRCH_FOREST: "桦木森林"
  COLD_OCEAN: "冷水海洋"
  CRIMSON_FOREST: "绯红森林"
  CUSTOM: "自定义生态群系"
  DARK_FOREST: "黑森林"
  DEEP_COLD_OCEAN: "冷水深海"
  DEEP_DARK: "深邃洞穴"
  DEEP_FROZEN_OCEAN: "冰冻深海"
  DEEP_LUKEWARM_OCEAN: "温水深海"
  DEEP_OCEAN: "深海"
  DESERT: "沙漠"
  DRIPSTONE_CAVES: "溶洞"
  END_BARRENS: "末地荒地"
  END_HIGHLANDS: "末地高地"
  END_MIDLANDS: "末地内陆"
  ERODED_BADLANDS: "被风蚀的恶地"
  FLOWER_FOREST: "繁花森林"
  FOREST: "森林"
  FROZEN_OCEAN: "冻洋"
  FROZEN_PEAKS: "冰封山峰"
  FROZEN_RIVER: "冻河"
  GROVE: "雪林"
  ICE_SPIKES: "冰刺平原"
  JAGGED_PEAKS: "尖峭山峰"
  JUNGLE: "丛林"
  LUKEWARM_OCEAN: "温水海洋"
  LUSH_CAVES: "繁茂洞穴"
  MANGROVE_SWAMP: "红树林沼泽"
  MEADOW: "草甸"
  MUSHROOM_FIELDS: "蘑菇岛"
  NETHER_WASTES: "下界荒地"
  OCEAN: "海洋"
  OLD_GROWTH_BIRCH_FOREST: "原始桦木森林"
  OLD_GROWTH_PINE_TAIGA: "原始松木针叶林"
  OLD_GROWTH_SPRUCE_TAIGA: "原始云杉针叶林"
  PLAINS: "平原"
  RIVER: "河流"
  SAVANNA: "热带草原"
  SAVANNA_PLATEAU: "热带高原"
  SMALL_END_ISLANDS: "末地小型岛屿"
  SNOWY_BEACH: "积雪沙滩"
  SNOWY_PLAINS: "积雪平原"
  SNOWY_SLOPES: "积雪山坡"
  SNOWY_TAIGA: "积雪针叶林"
  SOUL_SAND_VALLEY: "灵魂沙峡谷"
  SPARSE_JUNGLE: "稀疏的丛林"
  STONY_PEAKS: "裸岩山峰"
  STONY_SHORE: "石岸"
  SUNFLOWER_PLAINS: "向日葵平原"
  SWAMP: "沼泽"
  TAIGA: "针叶林"
  THE_END: "末地"
  THE_VOID: "虚空"
  WARM_OCEAN: "暖水海洋"
  WARPED_FOREST: "诡异森林"
  WINDSWEPT_FOREST: "风袭森林"
  WINDSWEPT_GRAVELLY_HILLS: "风袭沙砾丘陵"
  WINDSWEPT_HILLS: "风袭丘陵"
  WINDSWEPT_SAVANNA: "风袭热带草原"
  WOODED_BADLANDS: "繁茂的恶地"